# my global config
global:
  scrape_interval: 1s       # scrape every second
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "ai_trading_bot"

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "hft_engine"
